baseURL = "https://zhuygln.github.io/"
languageCode = "en-us"
title = "Yong-Lin Zhu"
disableKinds = ["taxonomy", "term"]

[params]
  email = "zhuygln@gmail.com"
  accent = "#ed5126"
  description = "Nuclear Astrophysics Research"
  github = "https://github.com/zhuygln"
  scholar = "https://scholar.google.com/citations?user=5zl5bT4AAAAJ&hl=en"
  inspirehep = "http://inspirehep.net/author/profile/Yong.Lin.Zhu.1"
